[project]
name = "vigor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Travis Luckenbaugh", email = "tluckenbaugh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "waitress>=3.0.2",
    "requests>=2.32.0",
]

[project.scripts]
vigor = "vigor.cli:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"